# Generated by Django 3.0.7 on 2022-02-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, default='', max_length=50)),
                ('result', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
